"""initial

Revision ID: 7fd37837a113
Revises: 
Create Date: 2026-01-04 05:11:19.477019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fd37837a113'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('last_activity', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('notify_hours', postgresql.ARRAY(sa.SMALLINT()), server_default=sa.text("'{}'::smallint[]"), nullable=False),
    sa.Column('time_zone_delta', sa.SMALLINT(), nullable=False),
    sa.CheckConstraint('array_length(notify_hours, 1) <= 24', name='check_notify_hours_max_length'),
    sa.CheckConstraint('notify_hours <@ ARRAY[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]::smallint[]', name='check_notify_hours_range'),
    sa.CheckConstraint('time_zone_delta BETWEEN -12 AND 12', name='check_timezone_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_notify_hours', 'users', ['notify_hours'], unique=False, postgresql_using='gin')
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('utc_date', sa.DATE(), nullable=False),
    sa.Column('utc_hour', sa.SMALLINT(), nullable=False),
    sa.CheckConstraint('utc_hour BETWEEN 0 AND 23', name='check_hour_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'utc_date', 'utc_hour', name='uix_user_id_time')
    )
    op.create_index('ix_activity_date_hour', 'activities', ['utc_date', 'utc_hour'], unique=False)
    op.create_index('ix_activity_user_date', 'activities', ['user_id', 'utc_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_user_date', table_name='activities')
    op.drop_index('ix_activity_date_hour', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_users_notify_hours', table_name='users', postgresql_using='gin')
    op.drop_table('users')
    # ### end Alembic commands ###
