"""Add time zone delta field for user

Revision ID: ce55c6ad0783
Revises: bcf7105ce2e6
Create Date: 2025-01-02 02:10:29.701493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce55c6ad0783'
down_revision: Union[str, None] = 'bcf7105ce2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('time_zone_delta', sa.SMALLINT(), nullable=False, default=0, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_zone_delta')
    # ### end Alembic commands ###
